### ISSUE TITLE
21 goal categories of RedNet model?

### ISSUE THREAD

**Issue by zenght** [joel99/objectnav#2]
## ❓ Questions and Help
Hey folks, thanks for your sharing,  your work is amazing. As discussed in A.15 Rednet Tuning, the 21 goal categories RedNet is used in the main text. But, I noticed that the number classed of the provided model “rednet_semmap_mp3d_tuned.pth” is still 40. How can i get the 21 goal categories RedNet mentioned in the article.

**Comment by joel99** [comment]
Thanks for asking! For simplicity during fine-tuning, both 21 and 40 category RedNet experiments use 40 category architectures, but the 21 category RedNet should not be predicting any of the non-goal categories. Let me know if this isn't the case.

Best,
Joel

**Comment by zenght** [comment]
> Thanks for asking! For simplicity during fine-tuning, both 21 and 40 category RedNet experiments use 40 category architectures, but the 21 category RedNet should not be predicting any of the non-goal categories. Let me know if this isn't the case.
> 
> Best,
> Joel

Thanks for your reply, this has resolved my concerns
