### ISSUE TITLE
Minimal Example

### ISSUE THREAD

**Issue by lukasmajer** [joel99/objectnav#3]
## ❓ Questions and Help
Hi, first of all, thank you for your amazing work. From the paper, it is obvious your results are really pushing the state of the art in ObjectNav.

I am trying to reproduce your results for my own research/paper and I have run into some obstacles. Thus I come here with a small list of suggestions/pleas.

1) Would you be willing to provide a minimal example of Agent implementation with your code? I have trouble extracting the basic act/reset interface from your code. 

2) I suggest taking a look at the environment definition in enviroment.yml. Solving it in Conda took almost two hours and it required quite a lot of tinkering to actually get it up and running. Are all of the packages listed there really necessary?

3) Would it be possible to unify configuration files? There are multiple files with not-so-clear naming/ numbering conventions and it is hard for me to keep track of them.

Thanks, Lukas

**Comment by joel99** [comment]
Hi Lukas,

I'm sorry to hear you ran into trouble with the code. Here are my thoughts, though:
1. This sounds reasonable - I can try to get the simple agent interface used in the challenge with weights loaded. Will ping back when that is done.

2. There are possibly some extra packages in the `environment.yml`, but as I ran my experiments with this configuration I am leaving it for reproducibility. I'd be interested to hear what tinkering was necessary.

3. I am providing all the configurations under `/objectnav`, one for each experiment, that correspond with the names in the paper. The ones that set benchmark records are marked in the readme.

**Comment by lukasmajer** [comment]
> Hi Lukas,
> 
> I'm sorry to hear you ran into trouble with the code. Here are my thoughts, though:
> 
> 1. This sounds reasonable - I can try to get the simple agent interface used in the challenge with weights loaded. Will ping back when that is done.
> 2. There are possibly some extra packages in the `environment.yml`, but as I ran my experiments with this configuration I am leaving it for reproducibility. I'd be interested to hear what tinkering was necessary.
> 3. I am providing all the configurations under `/objectnav`, one for each experiment, that correspond with the names in the paper. The ones that set benchmark records are marked in the readme.

Thank you for such a swift response.

1) That would be brilliant. Thank you.

2) I had trouble with the torch.jit module (some function missing I think). Solved by trying out different versions of torchvision. This led to sometimes failing the following check:

StrictVersion(torch.__version__) >= StrictVersion("1.6.0")

even though the version was correct. It's solved now though.

3) Ok, I will go over it one more time. Thanks.

Lukas

**Comment by joel99** [comment]
Hi Lukas -- I've opened my challenge submission agent to the public, which can be found here: 
https://github.com/joel99/habitat-challenge

Hope this helps. Sorry for the delay.

**Comment by lukasmajer** [comment]
Hi Joel,
I will check it out next week and close the issue after. Thank you so much for your work.
