### ISSUE TITLE
Pretrained ResNet18-RGBD missing

### ISSUE THREAD

**Issue by tommyz94** [joel99/objectnav#4]
## ❓ Questions and Help
Hi Joel,
Thanks for your exciting work. I'm trying to retrain your model, but I think that the pretrained resnet18 model is missing. I'm referring to the file reported in obj_base.on.yaml under RL.PPO.POLICY.pretrained_weights (resnet-18-mp3d-rgbd-100m.pth). 

Thank you very much,
Tommaso

**Comment by joel99** [comment]
Hello,

Sorry -- I currently haven't uploaded those separate weights, but the uploaded models contain resnet weights as well, post ObjNav training. Are those usable?

**Comment by tommyz94** [comment]
Hi Joel,
First of all, thank you for your reply. The post-training weights are different from the initial ones? Is it possible for you to upload also those weights in the Google Drive folder? Because I would like to try some modifications and I want to retrain the model from scratch.

**Comment by joel99** [comment]
Hey, I've uploaded the weights. Apologies for the delay.
