### ISSUE TITLE
finetuned Rednet

### ISSUE THREAD

**Issue by haokuanluo** [joel99/objectnav#5]
## ❓ Questions and Help
Hi Joel,

Thank you so much for sharing your work!

I have a question regarding the use of the fine-tuned rednet:
I was trying to use the rednet with the fine-tuned weight for semantic prediction on habitat;
However, I find out that rednet predicts around 30 categories, instead of 21. I was wondering whether this means I was using the rednet in the wrong way, or is that normal?
For more details, I fed in the raw sensor input of RGBD into the rednet. Is there supposed to be any preprocessing before feeding into the rednet?

Thank you!

Haokuan

**Comment by joel99** [comment]
What do you mean by "around 30"? I expect that the rednet files to provide a shape with 40 predictions (all possible MP3D categories), but possibly have all but 21 as 0 probabilities. #2 seems relevant.

There shouldn't be any pre-processing beyond what is done in the code currently

**Comment by haokuanluo** [comment]
I treat a category as "predicted" if their score is > 10 and they receive the highest score among all 40 channels. In the end, there are about 30 categories that reach this condition, which conflicts with #2, so I thought I might have done something wrong. 

I fed the raw sensor input into the "RedNetResizeWrapper" directly without any pre-processing before that, was that how it was supposed to be used?

Thank you so much!

**Comment by joel99** [comment]
Feeding in the raw sensor input is correct. There are two weights uploaded, `rednet_semmap_mp3d_tuned` which should output 21 classes, and `rednet_semmap_mp3d_40` which should output 40. I guess you're using the former, and I'm surprised you're finding 30 classes. Honestly, the code doesn't strictly check RedNet puts out 21 classes, so your issue may be an oversight on my part -- I would suggest casting non-goal categories to void manually if you want to make it strict. You'll see in `resnet.py` that I embed 40ish classes regardless of the RedNet that's used, as in my training I use all 40 simulator classes.

Hope this helps!

**Comment by haokuanluo** [comment]
Thank you! That has resolved my concern. It turns out that there are more than 21 classes predicted, but far less than the 40 categories one. 
Thank you so much!
