### ISSUE TITLE
The effect of adding semantic segmentation to the visual input

### ISSUE THREAD

**Issue by xlnwel** [joel99/objectnav#6]
## ❓ Questions and Help

Hi, 

Thank you for your great work. I'm wondering the effect of adding semantic segmentation to the visual input. As you pointed out in the Section 3.1 of your paper, the semantic segmentation is of low quality and unstable. Then why do you still provide it in the visual input? Why not feed in the depth image instead?

**Comment by joel99** [comment]
Depth is also provided. Two answers to this: 1. we use noiseless semantics during training, but even noisy information is useful as information (e.g. Treasure Hunt Data Augmentation by Maksymets et al. trains with noisy semantics entirely). Hope this helps.

**Comment by xlnwel** [comment]
Hi @joel99 

Thank you for the answer. That resolved my question.
